import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import dynamic from 'next/dynamic'
const NavBar = dynamic(() => import('../components/navbar/Navbar'), { ssr: false })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
        <NavBar />
        {children}
        </div>
        
        </body>
    </html>
  );
}
